#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/dist-native"
APP="$OUT/Duxo.app"
CONTENTS="$APP/Contents"
RESOURCES="$CONTENTS/Resources"
MACOS="$CONTENTS/MacOS"

rm -rf "$OUT"
mkdir -p "$MACOS" "$RESOURCES/ui" "$RESOURCES/duxo-runtime"

swiftc \
  -O \
  -whole-module-optimization \
  -target arm64-apple-macosx15.0 \
  -framework AppKit \
  -framework WebKit \
  "$ROOT/macos/DuxoNative.swift" \
  -o "$MACOS/Duxo"

chmod 755 "$MACOS/Duxo"
cp "$ROOT/macos/Info.plist" "$CONTENTS/Info.plist"
cp -R "$ROOT/dist-renderer/." "$RESOURCES/ui/"
node "$ROOT/scripts/stage-runtime.mjs"

ANALYZER="$ROOT/resources/duxo-analyzer"
ADAPTER="$ROOT/resources/duxo-adapter"
if [[ ! -x "$ANALYZER" ]]; then echo "Missing executable Analyzer: $ANALYZER" >&2; exit 1; fi
if [[ ! -x "$ADAPTER" ]]; then echo "Missing executable Adapter: $ADAPTER" >&2; exit 1; fi
cp "$ANALYZER" "$RESOURCES/duxo-runtime/duxo-analyzer"
cp "$ADAPTER" "$RESOURCES/duxo-runtime/duxo-adapter"
chmod 755 "$RESOURCES/duxo-runtime/duxo-analyzer" "$RESOURCES/duxo-runtime/duxo-adapter"

node "$ROOT/scripts/prepare-icons.mjs"
ICON_ICNS="$ROOT/build/icon.icns"
if [[ ! -s "$ICON_ICNS" ]]; then echo "Missing generated Duxo icon: $ICON_ICNS" >&2; exit 1; fi
cp "$ICON_ICNS" "$RESOURCES/Duxo.icns"
/usr/bin/plutil -replace CFBundleIconFile -string Duxo "$CONTENTS/Info.plist"

BUILD_SHA="${GITHUB_SHA:-local}"
BUILD_VERSION="$(/usr/bin/plutil -extract CFBundleShortVersionString raw "$CONTENTS/Info.plist")"
cat > "$RESOURCES/Duxo-Build.txt" <<EOF
Duxo native macOS build
Host: AppKit + WKWebView
Architecture: arm64
Electron runtime: not used
Icon: Duxo.icns generated by prepare-icons.mjs
Validation profile: native-macos-v5
Build version: $BUILD_VERSION
Git SHA: $BUILD_SHA
Distribution: ZIP + DMG
Runtime: Analyzer + Adapter
EOF

/usr/bin/plutil -lint "$CONTENTS/Info.plist"
chmod 755 "$MACOS/Duxo" "$RESOURCES/duxo-runtime/duxo-analyzer" "$RESOURCES/duxo-runtime/duxo-adapter"

SIGNING_IDENTITY="${APPLE_SIGNING_IDENTITY:--}"
if [[ "$SIGNING_IDENTITY" == "-" ]]; then
  echo "Code signing mode: ad-hoc"
  /usr/bin/codesign --force --sign - "$APP"
else
  echo "Code signing mode: identity $SIGNING_IDENTITY"
  /usr/bin/codesign --force --options runtime --sign "$SIGNING_IDENTITY" "$APP"
fi

/usr/bin/codesign --verify --deep --strict --verbose=2 "$APP"
/usr/bin/codesign --display --verbose=4 "$APP" || true
/usr/bin/file "$MACOS/Duxo"
/usr/bin/file "$RESOURCES/Duxo.icns"
/usr/bin/file "$RESOURCES/duxo-runtime/duxo-analyzer"
/usr/bin/file "$RESOURCES/duxo-runtime/duxo-adapter"

ZIP="$OUT/Duxo-Native-macos-arm64.zip"
rm -f "$ZIP"
/usr/bin/ditto -c -k --sequesterRsrc --keepParent "$APP" "$ZIP"
/usr/bin/shasum -a 256 "$ZIP" | /usr/bin/tee "$OUT/Duxo-Native-macos-arm64.zip.sha256"

DMG="$OUT/Duxo-Native-macos-arm64.dmg"
DMG_STAGE="$OUT/.dmg-stage"
rm -rf "$DMG_STAGE" "$DMG"
mkdir -p "$DMG_STAGE"
/usr/bin/ditto "$APP" "$DMG_STAGE/Duxo.app"
ln -s /Applications "$DMG_STAGE/Applications"
/usr/bin/hdiutil create -volname "Duxo" -srcfolder "$DMG_STAGE" -ov -format UDZO "$DMG"
rm -rf "$DMG_STAGE"

MOUNT_INFO="$(/usr/bin/hdiutil attach "$DMG" -nobrowse -noautoopen)"
MOUNT_PATH="$(printf '%s\n' "$MOUNT_INFO" | awk -F'\t' '/\/Volumes\// {print $NF; exit}')"
if [[ -z "$MOUNT_PATH" ]]; then echo "DMG validation failed: could not mount $DMG" >&2; exit 1; fi
trap '/usr/bin/hdiutil detach "$MOUNT_PATH" -quiet >/dev/null 2>&1 || true' EXIT

test -d "$MOUNT_PATH/Duxo.app"
test -d "$MOUNT_PATH/Applications"
test -x "$MOUNT_PATH/Duxo.app/Contents/MacOS/Duxo"
test -f "$MOUNT_PATH/Duxo.app/Contents/Resources/Duxo.icns"
test -x "$MOUNT_PATH/Duxo.app/Contents/Resources/duxo-runtime/duxo-analyzer"
test -x "$MOUNT_PATH/Duxo.app/Contents/Resources/duxo-runtime/duxo-adapter"
/usr/bin/codesign --verify --deep --strict --verbose=2 "$MOUNT_PATH/Duxo.app"
/usr/bin/hdiutil detach "$MOUNT_PATH" -quiet
trap - EXIT

/usr/bin/shasum -a 256 "$DMG" | /usr/bin/tee "$OUT/Duxo-Native-macos-arm64.dmg.sha256"
printf 'Native macOS ZIP: %s\n' "$ZIP"
printf 'Native macOS DMG: %s\n' "$DMG"
printf 'ZIP checksum: %s\n' "$OUT/Duxo-Native-macos-arm64.zip.sha256"
printf 'DMG checksum: %s\n' "$OUT/Duxo-Native-macos-arm64.dmg.sha256"
